# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apigee-cassandra-user-setup-srinandans-hybr-cb84b88-sa
  namespace: apigee
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apigee-cassandra-schema-setup-srinandans-hybr-cb84b88-sa
  namespace: apigee
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apigee-mart-srinandans-hybr-cb84b88-sa
  namespace: apigee
  annotations:
    iam.gke.io/gcp-service-account: apigee-mart@nandanks-151422.iam.gserviceaccount.com
  labels:
    org: srinandans-hybrid
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apigee-connect-agent-srinandans-hybr-cb84b88-sa
  namespace: apigee
  annotations:
    iam.gke.io/gcp-service-account: apigee-connect@nandanks-151422.iam.gserviceaccount.com
  labels:
    org: srinandans-hybrid
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: apigee-watcher-srinandans-hybr-cb84b88-sa
  namespace: apigee
  annotations:
    iam.gke.io/gcp-service-account: apigee-watcher@nandanks-151422.iam.gserviceaccount.com
  labels:
    org: srinandans-hybrid    
---
apiVersion: apigee.cloud.google.com/v1alpha1
kind: ApigeeOrganization
metadata:
  name: "srinandans-hybr-cb84b88"
  namespace: "apigee"
release:
  forceUpdate: true
spec:
  imagePullSecrets:
    - name: gcrsecret
  name: "srinandans-hybrid"
  datastoreRef: "default"
  datastoreCredentialRef: "default-datastore-creds"
  dataEncryptionRef: "srinandans-hybr-cb84b88-data-encryption"
  redisRef: "default"
  axHashingSaltRef: "srinandans-hybr-cb84b88-ax-salt"
  apigeeEndpoint: "https://apigee.googleapis.com"
  apigeeConnectEndpoint: "apigeeconnect.googleapis.com:443"
  instanceID: "us-west1"
  clusterName: "srinandans-hybrid"
  clusterRegion: "us-west1"
  gcpProjectID: "nandanks-151422"
  components:
    cassandraUserSetup:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 998
        privileged: false
      podServiceAccountName: apigee-cassandra-user-setup-srinandans-hybr-cb84b88-sa
      nodeAffinityRequired: true
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cloud.google.com/gke-nodepool
              operator: In
              values:
              - apigee-runtime
      initContainers:
      - name: "apigee-cassandra-readiness"
        image: "us.gcr.io/google.com/edge-ci/integration/data-services/apigee-hybrid-cassandra-client/1.5.0/apigee-cassandra-client:20041_06c26d8"
        imagePullPolicy: IfNotPresent
      containers:
      - name: "apigee-cassandra-user-setup"
        image: "us.gcr.io/google.com/edge-ci/integration/data-services/apigee-hybrid-cassandra-client/1.5.0/apigee-cassandra-client:20041_06c26d8"
        imagePullPolicy: IfNotPresent
    cassandraSchemaSetup:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 998
        privileged: false
      podServiceAccountName: apigee-cassandra-schema-setup-srinandans-hybr-cb84b88-sa
      nodeAffinityRequired: true
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cloud.google.com/gke-nodepool
              operator: In
              values:
              - apigee-runtime
      initContainers:
      - name: "apigee-cassandra-user-readiness"
        image: "us.gcr.io/google.com/edge-ci/integration/data-services/apigee-hybrid-cassandra-client/1.5.0/apigee-cassandra-client:20041_06c26d8"
        imagePullPolicy: IfNotPresent
      containers:
      - name: "apigee-cassandra-schema-setup"
        image: "us.gcr.io/google.com/edge-ci/integration/featureplatform/apigee-mart-server/1.5.0/apigee-mart-server:21314_5af2bb0"
        imagePullPolicy: IfNotPresent
    connectAgent:
      podServiceAccountName: apigee-connect-agent-srinandans-hybr-cb84b88-sa
      nodeAffinityRequired: true
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cloud.google.com/gke-nodepool
              operator: In
              values:
              - apigee-runtime
      version: "150rc1"
      autoScaler:
        minReplicas: 1
        maxReplicas: 1
        metrics:
        - type: Resource
          resource:
            name: cpu
            targetAverageUtilization: 75
      containers:
      - name: "apigee-connect-agent"
        image: "us.gcr.io/google.com/edge-ci/integration/featureplatform/apigee-connect-agent/master:20518_946872d"
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            cpu: 200m
            memory: 128Mi        
          requests:
            cpu: 200m
            memory: 128Mi
        env:
        - name: GRPC_GO_LOG_SEVERITY_LEVEL
          value: "ERROR"
        - name: LOG_VERBOSITY_LEVEL
          value: "0"
    watcher:
      podServiceAccountName: apigee-watcher-srinandans-hybr-cb84b88-sa
      nodeAffinityRequired: true
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cloud.google.com/gke-nodepool
              operator: In
              values:
              - apigee-runtime
      version: "150rc1"
      #nandan fix
      #appServiceAccountSecretName: "apigee-watcher-srinandans-hybr-cb84b88-svc-account"
      autoScaler:
        minReplicas: 1
        maxReplicas: 1
      containers:
      - name: "apigee-watcher"
        image: "us.gcr.io/google.com/edge-ci/integration/eda/apigee-watcher/master/watcher:20313_376b60f"
        imagePullPolicy: "IfNotPresent"
      properties:
        mintRecurringJobImage: ":"
    mart:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 998
        privileged: false
      podServiceAccountName: apigee-mart-srinandans-hybr-cb84b88-sa
      nodeAffinityRequired: true
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: cloud.google.com/gke-nodepool
              operator: In
              values:
              - apigee-runtime
      version: "150rc1"
      autoScaler:
        minReplicas: 1
        maxReplicas: 5
        metrics:
        - type: Resource
          resource:
            name: cpu
            targetAverageUtilization: 75
      initContainers:
      - name: apigee-cassandra-schema-readiness
        image: "us.gcr.io/google.com/edge-ci/integration/featureplatform/apigee-mart-server/1.5.0/apigee-mart-server:21314_5af2bb0"
        imagePullPolicy: "IfNotPresent"
      containers:
      - name: "apigee-authz"
        image: "us.gcr.io/google.com/edge-ci/integration/featureplatform/apigee-authn-authz/master:20065_af30595"
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            cpu: 25m
            memory: 128Mi          
          requests:
            cpu: 25m
            memory: 128Mi
        readinessProbe:
          httpGet:
            path: /healthz
            port: 7091
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 2
        livenessProbe:
          httpGet:
            path: /healthz
            port: 7091
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 2
      - name: "apigee-mart"
        image: "us.gcr.io/google.com/edge-ci/integration/featureplatform/apigee-mart-server/1.5.0/apigee-mart-server:21314_5af2bb0"
        imagePullPolicy: "IfNotPresent"
        livenessProbe:
          httpGet:
            path: /v1/probes/live
            scheme: HTTPS
            port: 8843
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 12
        readinessProbe:
          httpGet:
            path: /v1/probes/ready
            scheme: HTTPS
            port: 8843
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 2
        resources:
          limits:
            cpu: 500m
            memory: 512Mi        
          requests:
            cpu: 500m
            memory: 512Mi
        env:
        - name: "SRINANDANS_HYBRID_KMS_ENCRYPTION_KEY"
          valueFrom:
            secretKeyRef:
              name: "srinandans-hybr-cb84b88-encryption-keys"
              key: kmsEncryptionKey
      - name: "apigee-authz"
        image: "us.gcr.io/google.com/edge-ci/integration/featureplatform/apigee-authn-authz/master:20065_af30595"
        imagePullPolicy: "IfNotPresent"
        resources:
          limits:
            cpu: 25m
            memory: 128Mi                  
          requests:
            cpu: 25m
            memory: 128Mi
---