# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apigee.cloud.google.com/v1alpha1
kind: ApigeeDatastore
metadata:
  name: default
  labels:
    apigee.cloud.google.com/platform: apigee
spec:
  replicas: 1
  credentialRef: apigee-datastore-default-creds
  components:
    removeDc:
      containers:
        - name: apigee-cassandra-remove-dc
          image: gcr.io/apigee-release/hybrid/apigee-hybrid-cassandra-client:1.6.3
          imagePullPolicy: IfNotPresent
    cassandra:
      hostNetwork: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 998
        privileged: false
        capabilities:
          add:
            - IPC_LOCK
            - SYS_RESOURCE
      podServiceAccountName: apigee-datastore-default-sa
      properties:
        clusterName: apigeecluster
        datacenter: dc-1
        rack: ra-1
      storage:
        storageSize: 10Gi
      volumes:
        - name: apigee-cassandra-backup
          secret:
            defaultMode: 420
            secretName: apigee-cassandra-backup-svc-account
            optional: true
        - name: apigee-cassandra-backup-key-file
          secret:
            defaultMode: 256
            secretName: apigee-cassandra-backup-key-file
            optional: true
      containers:
        - name: apigee-cassandra
          image: gcr.io/apigee-release/hybrid/apigee-hybrid-cassandra:1.6.3
          imagePullPolicy: IfNotPresent
          readinessProbe:
            exec:
              command:
                - /bin/bash
                - -c
                - /opt/apigee/ready-probe.sh
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 2
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
          env:
            - name: MAX_HEAP_SIZE
              value: 512M
            - name: HEAP_NEWSIZE
              value: 100M
            - name: APIGEE_CLOUDPROVIDER
              value: GCP
            - name: DBSTORAGE_BUCKET
              value: gs://nandanks-backup
          volumeMounts:
            - name: apigee-cassandra-backup
              mountPath: /var/secrets/google
            - name: apigee-cassandra-backup-key-file
              mountPath: /var/secrets/keys
