# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- patch: |-
    - op: replace
      path: /spec/components/cassandra/containers/0/resources/requests/cpu
      value: 7
  target:
    group: apigee.cloud.google.com
    kind: ApigeeDatastore
    name: .*
    version: v1alpha1
- patch: |-
    - op: replace
      path: /spec/components/cassandra/containers/0/resources/requests/memory
      value: 15Gi
  target:
    group: apigee.cloud.google.com
    kind: ApigeeDatastore
    name: .*
    version: v1alpha1
- patch: |-
    - op: replace
      path: /spec/components/cassandra/storage/storageSize
      value: 500Gi
  target:
    group: apigee.cloud.google.com
    kind: ApigeeDatastore
    name: .*
    version: v1alpha1
- patch: |-
    - op: replace
      path: /spec/components/cassandra/containers/0/env/0/value
      value: 8192M
  target:
    group: apigee.cloud.google.com
    kind: ApigeeDatastore
    name: .*
    version: v1alpha1
- patch: |-
    - op: replace
      path: /spec/components/cassandra/containers/0/env/1/value
      value: 1200M
  target:
    group: apigee.cloud.google.com
    kind: ApigeeDatastore
    name: .*
    version: v1alpha1
