# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is the role that will be associated to the above service account.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apigee
rules:
  - apiGroups: ["*"]
    resources: ["secrets"]
    verbs: ["get", "create", "watch"]
  - apiGroups: ["cert-manager.io"]
    resources: ["issuers", "certificates", "clusterissuers"]
    verbs: ["get", "create", "watch"]
---
# Binding the role to the service account.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apigee
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apigee
subjects:
  - kind: ServiceAccount
    name: apigee
    namespace: apigee-system
---
# This is the role that will be associated to the above service account.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apigee-init
rules:
  - apiGroups: ["*"]
    resources: ["secrets"]
    verbs: ["get", "create", "watch"]
---
# Binding the role to the service account.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apigee-init
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apigee-init
subjects:
  - kind: ServiceAccount
    name: apigee-init
    namespace: apigee
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apigee-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumes
  - pods
  verbs:
  - get
  - list
- apiGroups:
  - ""
  resources:
  - persistentvolumes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  - services
  verbs:
  - batch
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  - apps
  - authentication.istio.io
  - autoscaling
  - networking.istio.io
  - security.istio.io
  resources:
  - destinationrules
  - events
  - horizontalpodautoscalers
  - peerauthentications
  - policies
  - replicasets
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  - networking.istio.io
  resources:
  - events
  - gateways
  - virtualservices
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeedatastores
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeedatastores/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeedatastores/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeedeployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeedeployments/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeedeployments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeeenvironments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeeenvironments/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeeenvironments/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeeorganizations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeeorganizations/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeeorganizations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeerouteconfigs
  verbs:
  - get
  - list
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeeroutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeeroutes/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeeroutes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeetelemetries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeetelemetries/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - apigeetelemetries/status
  verbs:
  - get
  - list
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - cassandradatareplications
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - cassandradatareplications/finalizers
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apigee.cloud.google.com
  resources:
  - cassandradatareplications/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - apps
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - issuers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apigee-proxy-role
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apigee-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apigee-manager-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: apigee-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apigee-proxy-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apigee-proxy-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: apigee-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apigee-watcher-srinandans-hybr-cb84b88
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apigee-watcher-srinandans-hybr-cb84b88
subjects:
- kind: ServiceAccount
  name: apigee-watcher-srinandans-hybr-cb84b88-sa
  namespace: apigee
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apigee-metrics-apigee-telemetry
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: apigee-metrics-apigee-telemetry
subjects:
- kind: ServiceAccount
  name: apigee-metrics-svc
  namespace: apigee
- kind: ServiceAccount
  name: apigee-metrics-svc
  namespace: apigee  