# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apigee.cloud.google.com/v1alpha2
kind: ApigeeEnvironment
metadata:
  name: env
  labels:
    apigee.cloud.google.com/platform: apigee
release:
  forceUpdate: true
spec:
  name: prod1
  organizationRef: org
  components:
    synchronizer:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 998
        privileged: false
      podServiceAccountName: apigee-synchronizer-env-sa
      autoScaler:
        minReplicas: 1
        maxReplicas: 1
        metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 75
      initContainers:
        - name: apigee-cassandra-schema-readiness
          image: gcr.io/apigee-release/hybrid/apigee-mart-server:1.6.3
          imagePullPolicy: IfNotPresent
      containers:
        - name: apigee-synchronizer
          image: gcr.io/apigee-release/hybrid/apigee-synchronizer:1.6.3
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /v1/probes/live
              scheme: HTTPS
              port: 8843
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /v1/probes/ready
              scheme: HTTPS
              port: 8843
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 2
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
    udca:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 998
        privileged: false
      podServiceAccountName: apigee-udca-env-sa
      autoScaler:
        minReplicas: 1
        maxReplicas: 1
        metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 75
      initContainers:
        - name: apigee-tls-readiness
          image: gcr.io/apigee-release/hybrid/apigee-udca:1.6.3
          imagePullPolicy: IfNotPresent
      containers:
        - name: apigee-udca
          image: gcr.io/apigee-release/hybrid/apigee-udca:1.6.3
          imagePullPolicy: IfNotPresent
          env:
            - name: NOOP_MODE
              value: "false"
          livenessProbe:
            httpGet:
              path: /v1/probes/live
              port: 7070
              scheme: HTTPS
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 2
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
        - name: apigee-fluentd
          image: gcr.io/apigee-release/hybrid/apigee-stackdriver-logging-agent:1.8.9
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 128Mi
    runtime:
      podServiceAccountName: apigee-runtime-env-sa
      autoScaler:
        minReplicas: 1
        maxReplicas: 1
        metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 75
      configOverride:
        conf_metrics_server.metrics.latency.histogram.buckets.milliseconds: BUCKETS,1D,2D,5D,10D,25D,50D,75D,100D,250D,500D,750D,1000D,2500D,5000D,7500D,10000D
      initContainers:
        - name: apigee-cassandra-schema-readiness
          image: gcr.io/apigee-release/hybrid/apigee-mart-server:1.6.3
          imagePullPolicy: IfNotPresent
        - name: apigee-redis-envoy-readiness
          image: gcr.io/apigee-release/hybrid/apigee-runtime:1.6.3
          imagePullPolicy: IfNotPresent
      containers:
        - name: apigee-runtime
          image: gcr.io/apigee-release/hybrid/apigee-runtime:1.6.3
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /v1/probes/live
              scheme: HTTPS
              port: 8843
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /v1/probes/ready
              scheme: HTTPS
              port: 8843
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 2
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: java-sec-policy-volume
              readOnly: true
              mountPath: /opt/apigee/apigee-runtime/security
            - name: policy-secret-volume
              readOnly: true
              mountPath: /opt/apigee/apigee-runtime/policy-secrets
