# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apigee.cloud.google.com/v1alpha2
kind: ApigeeOrganization
metadata:
  name: org
  labels:
    apigee.cloud.google.com/platform: apigee
release:
  forceUpdate: true
spec:
  name: org
  datastoreRef: default
  datastoreCredentialRef: apigee-datastore-default-creds
  dataEncryptionRef: org-data-encryption
  redisRef: default
  axHashingSaltRef: org-ax-salt
  apigeeEndpoint: https://apigee.googleapis.com
  apigeeConnectEndpoint: apigeeconnect.googleapis.com:443
  instanceID: instance
  clusterName: org
  clusterRegion: region
  gcpProjectID: project
  components:
    cassandraUserSetup:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 998
        privileged: false
      podServiceAccountName: apigee-cassandra-user-setup-org-sa
      initContainers:
        - name: apigee-cassandra-readiness
          image: gcr.io/apigee-release/hybrid/apigee-hybrid-cassandra-client:1.6.3
          imagePullPolicy: IfNotPresent
      containers:
        - name: apigee-cassandra-user-setup
          image: gcr.io/apigee-release/hybrid/apigee-hybrid-cassandra-client:1.6.3
          imagePullPolicy: IfNotPresent
    cassandraSchemaSetup:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 998
        privileged: false
      podServiceAccountName: apigee-cassandra-schema-setup-org-sa
      initContainers:
        - name: apigee-cassandra-user-readiness
          image: gcr.io/apigee-release/hybrid/apigee-hybrid-cassandra-client:1.6.3
          imagePullPolicy: IfNotPresent
      containers:
        - name: apigee-cassandra-schema-setup
          image: gcr.io/apigee-release/hybrid/apigee-mart-server:1.6.3
          imagePullPolicy: IfNotPresent
    connectAgent:
      podServiceAccountName: apigee-connect-agent-org-sa
      autoScaler:
        minReplicas: 1
        maxReplicas: 1
        metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 75
      containers:
        - name: apigee-connect-agent
          image: gcr.io/apigee-release/hybrid/apigee-connect-agent:1.6.3
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 200m
              memory: 128Mi
          env:
            - name: GRPC_GO_LOG_SEVERITY_LEVEL
              value: ERROR
            - name: LOG_VERBOSITY_LEVEL
              value: "0"
    watcher:
      podServiceAccountName: apigee-watcher-org-sa
      autoScaler:
        minReplicas: 1
        maxReplicas: 1
      containers:
        - name: apigee-watcher
          image: gcr.io/apigee-release/hybrid/apigee-watcher:1.6.3
          imagePullPolicy: IfNotPresent
      properties:
        mintRecurringJobImage: ':'
    mart:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 998
        privileged: false
      podServiceAccountName: apigee-mart-org-sa
      autoScaler:
        minReplicas: 1
        maxReplicas: 5
        metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 75
      initContainers:
        - name: apigee-cassandra-schema-readiness
          image: gcr.io/apigee-release/hybrid/apigee-mart-server:1.6.3
          imagePullPolicy: IfNotPresent
      containers:
        - name: apigee-authz
          image: gcr.io/apigee-release/hybrid/apigee-authn-authz:1.6.3
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
          readinessProbe:
            httpGet:
              path: /healthz
              port: 7091
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 2
          livenessProbe:
            httpGet:
              path: /healthz
              port: 7091
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 2
        - name: apigee-mart
          image: gcr.io/apigee-release/hybrid/apigee-mart-server:1.6.3
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /v1/probes/live
              scheme: HTTPS
              port: 8843
            initialDelaySeconds: 30
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 12
          readinessProbe:
            httpGet:
              path: /v1/probes/ready
              scheme: HTTPS
              port: 8843
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 2
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
        - name: apigee-authz
          image: gcr.io/apigee-release/hybrid/apigee-authn-authz:1.6.3
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 25m
              memory: 128Mi
    udca:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 998
        privileged: false
      podServiceAccountName: apigee-udca-org-sa
      autoScaler:
        minReplicas: 1
        maxReplicas: 1
        metrics:
          - type: Resource
            resource:
              name: cpu
              target:
                type: Utilization
                averageUtilization: 75
      initContainers:
        - name: apigee-tls-readiness
          image: gcr.io/apigee-release/hybrid/apigee-udca:1.6.3
          imagePullPolicy: IfNotPresent
      containers:
        - name: apigee-udca
          image: gcr.io/apigee-release/hybrid/apigee-udca:1.6.3
          imagePullPolicy: IfNotPresent
          env:
            - name: API_TENANT_GCS_UPLOAD_ENABLED
              value: "true"
            - name: NOOP_MODE
              value: "false"
          livenessProbe:
            httpGet:
              path: /v1/probes/live
              port: 7070
              scheme: HTTPS
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 2
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
        - name: apigee-fluentd
          image: gcr.io/apigee-release/hybrid/apigee-stackdriver-logging-agent:1.8.9
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              memory: 128Mi
