# config-management.yaml

apiVersion: configmanagement.gke.io/v1
kind: ConfigManagement
metadata:
  name: config-management
spec:
  # clusterName is required and must be unique among all managed clusters
  clusterName: srinandans-hybrid
  git:
    syncRepo: https://github.com/srinandan/srinandans-hybrid.git
    syncBranch: main
    secretType: token
  ConfigSyncPodResources:
    importer:
      limits:
        memory: "512Mi"
        cpu: "1"
      requests:
        memory: "256Mi"
        cpu: "150m"