apiVersion: v1
kind: Namespace
metadata:
  name: config-management-system
---
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: git-creds
  namespace: config-management-system
spec:
  backendType: vault
  vaultMountPoint: kubernetes
  vaultRole: external-secrets
  kvVersion: 2
  data:
  - name: token
    key: secret/data/srinandans-hybrid/github
    property: token
  - name: username
    key: secret/data/srinandans-hybrid/datastore
    property: username
